#mysql
spring:
  datasource:
    url: jdbc:mysql://120.79.246.100:3306/blogs?serverTimezone=GMT&useUnicode=true&characterEncoding=UTF-8&transformedBitIsBoolean=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Root12345
    driver-class-name: com.mysql.cj.jdbc.Driver

#mybatis-plus
mybatis-plus:
  # 配置扫描xml
  mapper-locations:
    classpath: classpath:/mapper/*Mapper.xml
    # 实体扫描，多个package用逗号或者分号分隔
    type-aliases-package: blogs.service.pojo
    global-config:
      # 逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: 3
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: 1
      #驼峰下划线转换
      db-column-underline: true
      #刷新mapper 调试神器
      refresh-mapper: true
      #数据库大写下划线转换
      capital-mode: true
      # Sequence序列接口实现类配置
      #key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
    configuration:
      map-underscore-to-camel-case: true
      # 缓存
      cache-enabled: false
      #配置JdbcTypeForNull
      jdbc-type-for-null: 'null'
